name: Docker Image CI

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      app_name:
        description: 'app_name'
        required: true
        default: 'renren-admin'
        type: choice
        options:
          - renren-admin
          - renren-api
      app_version:
        description: 'app_version'
        required: true
        type: string

env:
  DOCKERHUB_DOMAIN: registry.cn-hangzhou.aliyuncs.com
  DOCKERHUB_REPO: wang-kun

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKERHUB_DOMAIN }}
          username: ${{ secrets.ALI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ALI_DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: image Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ inputs.app_name }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            JAR_FILE=${{ inputs.app_name }}.jar
          tags: |
            ${{ env.DOCKERHUB_DOMAIN }}/${{ env.DOCKERHUB_REPO }}/${{ inputs.app_name }}:latest
            ${{ env.DOCKERHUB_DOMAIN }}/${{ env.DOCKERHUB_REPO }}/${{ inputs.app_name }}:${{ inputs.app_version }}