name: Docker Image CI

on:
  push:
    tags:
      - v*

env:
  DOCKERHUB_REPO: registry.cn-hangzhou.aliyuncs.com/wang-kun/ 
  APP_NAME_ADMIN: zxxzyy-admin
  APP_NAME_PORTAL: zxxzyy-portal
  IMAGE_NAME_ADMIN: ${{ DOCKERHUB_REPO }}${{ APP_NAME_ADMIN }}
  IMAGE_NAME_PORTAL: ${{ DOCKERHUB_REPO }}${{ APP_NAME_PORTAL }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    - name: mv downloaded files
      run: |
        mv zxxzyy-admin*.jar zxxzyy-admin/target
        mv zxxzyy-portal*.jar zxxzyy-portal/target
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ALI_DOCKERHUB_USERNAME }}
        password: ${{ secrets.ALI_DOCKERHUB_TOKEN }}
    - name: Generate App Version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
    - name: cd zxxzyy-admin
      run: cd zxxzyy-admin
    - name: zxxzyy-admin Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        build-args: |
          JAR_FILE=zxxzyy-admin-1.0-SNAPSHOT.jar
          APP_NAME=${{ env.APP_NAME_ADMIN }}
          APP_VERSION=${{ env.APP_VERSION }}
        tags: |
          ${{ env.IMAGE_NAME_ADMIN }}:latest
          ${{ env.IMAGE_NAME_ADMIN }}:${{ env.APP_VERSION }}
    - name: return dir
      run: cd -      
    - name: cd zxxzyy-portal
      run: cd zxxzyy-portal
    - name: zxxzyy-portal Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        build-args: |
          JAR_FILE=zxxzyy-portal-1.0-SNAPSHOT.jar
          APP_NAME=${{ env.APP_NAME_PORTAL }}
          APP_VERSION=${{ env.APP_VERSION }}
        tags: |
          ${{ env.IMAGE_NAME_PORTAL }}:latest
          ${{ env.IMAGE_NAME_PORTAL }}:${{ env.APP_VERSION }}
    - name: return dir
      run: cd -     